services:
  # PHP + Apache
  app:
    build: .
    container_name: php_apache
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: cabinet_management_system
      DB_USERNAME: root
      DB_PASSWORD:
    depends_on:
      - db
      - redis
    networks:
      - laravel_net

  # MySQL (use local image)
  db:
    image: mysql:latest  # or mysql:latest if that's the local image
    container_name: mysql_db
    pull_policy: never  # avoid pulling if image exists locally
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: cabinet_management_system
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_net

  # Redis
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - laravel_net

  # Composer (one-time install)
  composer:
    image: composer:latest
    container_name: composer_runner
    working_dir: /app
    volumes:
      - .:/app
    command: ["composer", "install", "--optimize-autoloader", "--no-dev", "--no-interaction"]

networks:
  laravel_net:
    driver: bridge

volumes:
  mysql_data:
    driver: local
